const Rize = require("rize");
const rize = new Rize();
rize.goto('http://127.0.0.1:8081/book')
    .click("#book-create")
    .waitForNavigation()
    .type('input#bookIsbn',"123456")
    .type('input#bookName','前端小白进阶史')
    .type('input#bookAuthor','小冲')
    .type('input#bookPress','小冲出版社')
    .type('input#bookPrice','100')
    .type('input#bookTime','2019-01-30')
    .type('input#bookImgUrl',"https://avatars1.githubusercontent.com/u/33478391?s=460&v=4")
    .type('textarea[name="book_introduction"]',"这是一本非常有趣的书")
    .click("#createBtn")
    .waitForNavigation(2000)
    .assertTitle('图书管理')
    .type('[name="book_name"]',"前端小白进阶史")
    .click("#searchBtn")
    .waitForNavigation()
    .assertSee('小冲出版社')
    .end()